### ISSUE TITLE
Transfer ownership to QuickLyric on GitHub

### ISSUE THREAD

**Issue by geecko86** [QuickLyric/fpcalc-android#2]

**Comment by svenoaks** [comment]
Dont have permission to create repo's in QuickLyric

**Comment by geecko86** [comment]
@svenoaks Hi Steve! It looks like the static libraries (.a files) in this repo all have links to your system (/users/steve/library/android/... etc.). This makes it impossible for me to compile fpcalc-android (not sure how jitpak was able to back in February, but it's not the case anymore).

I was been able to recompile the FFmpeg libraries, but not **libchromaprint.a**. Any chance you remember how you managed to do that? I'm only getting a libchromaprint.so file.

Would very much appreciate the help, even though you don't _have_ to. :+1:

**Comment by svenoaks** [comment]
It's as easy as changing a single line in one of the make files

https://github.com/acoustid/chromaprint/blob/64e6eee76365d1995cd4f9eb763641fc369e397c/CMakeLists.txt#L24

Looks like it might be it
